### ISSUE TITLE
[FIX] 상세 화면 내 사진 indicator 관련 이슈

### ISSUE THREAD

**Issue by eshc123** [woowa-techcamp-2022/android-banchan-05#44]
### 📌 내용
상세 화면에서 사진 indicator 가 스크롤 등으로 다시 bind 될 때마다 늘어나는 이슈

### 🛠 ToDo
- [x] indicator 포함한 view pager adapter 관련 수정

### 의견
저도 비슷한 문제가 있었는데 bindData() 등으로 onBindViewHolder에 adapter를 할당해줘서 bind될 때마다 새로 처리가 되는 문제가 있었습니다. 따로 onCreateViewHolder 에서 adpater를 할당하니 문제가 해결되어서 이런 방향으로 수정하면 어떨까 싶습니다.

### 관련 자료
<img width="250" src="https://user-images.githubusercontent.com/50227341/185267676-8270d1b4-33a8-481e-a1d8-e43c14983ba5.jpg">  <img width="250" src="https://user-images.githubusercontent.com/50227341/185267675-c95ca31b-78e3-417c-a7e8-3ef2c7d3d61f.jpg"> <img width="250" src="https://user-images.githubusercontent.com/50227341/185267670-0e9c749f-b357-494d-9be7-e0fd79a104c3.jpg">

**Comment by aurora32s** [comment]
!! 석준님! 에러 확인 감사합니다! 🤗
바로 수정하고 Slack으로 말씀드리겠습니다.
